### ISSUE TITLE
Unable to display points

### ISSUE THREAD

**Issue by B880b** [lavanet/lava#1244]
Issue tracker is **ONLY** used for reporting bugs. Support or new features should be discussed on [Lava's Discord channel](https://discord.gg/5VcqgwMmkA).

## Steps to Reproduce

1.
2.
3.
4.

------

👇 SECTIONS BELOW ARE NOT OBLIGATORY 👇

**Comment by shleikes** [comment]
Not relevant to this repo. Closing issue.
