### ISSUE TITLE
README.md: Broken link in litepaper: needs fixing

### ISSUE THREAD

**Issue by meetrick** [lavanet/lava#1430]
Issue tracker is **ONLY** used for reporting bugs. Support or new features should be discussed on [Lava's Discord channel](https://discord.gg/5VcqgwMmkA).

## Expected Behavior
When clicking on the litepaper link, the Lava litepaper should be accessible.

## Current Behavior
The link is broken, leading to a 404 error page.
<img width="273" alt="image" src="https://github.com/lavanet/lava/assets/19239345/59864567-4a50-438e-aad0-ae673e409791">

## Steps to Reproduce
1. Click the litepaper link in README.md

------

👇 SECTIONS BELOW ARE NOT OBLIGATORY 👇

## Possible Solution
Re-upload the litepaper to Lava or connect it with the correct link

**Comment by oren-lava** [comment]
Thank you for reporting this issue!
Fix can be found here: https://github.com/lavanet/lava/pull/1444

**Comment by meetrick** [comment]
- issue was closed by #1444
