### ISSUE TITLE
[Feature]: REST all provider chains

### ISSUE THREAD

**Issue by RuslanGlaznyov** [lavanet/lava#1572]
### Summary

Improve integration with UI 

### Problem Definition

For some UI improvements, it would be great to display the chains supported by other providers. A REST endpoint to get all provider chains would be very helpful.

### Proposed Feature

Add REST query to all provider chains
Analog to CLI  request
```bash 
lavad q pairing provider  <provider>
```

**Comment by Yaroms** [comment]
we already have this api on rest:
'/lavanet/lava/pairing/providers/{chainID}'
you can leave the chainid empty to get for all chains

**Comment by RuslanGlaznyov** [comment]
Thx! how to pass provider address and get all provider chains? Same as we do with cli in my example

**Comment by RuslanGlaznyov** [comment]
FYI @Yaroms ^^

**Comment by Yaroms** [comment]
here is an example of how to use it on the current version:
`http://127.0.0.1:1317/lavanet/lava/pairing/provider/lava%401fe44wl9686rnka5l3a5ph3ev7awpc366wpjdgu/`

**Comment by RuslanGlaznyov** [comment]
Thanks, close the then
