### ISSUE TITLE
Voting end time in gov proposal doesn't match with actual end of voting

### ISSUE THREAD

**Issue by hdmiimdh** [lavanet/lava#316]
Based on discord announcement proposal №32 was actually created at `2023-02-21T03:37:39 UTC+7` or `2023-02-20T21:37:39 UTC`.

<img width="851" alt="Screen Shot 2023-02-21 at 17 37 17" src="https://user-images.githubusercontent.com/27004732/220322067-22cdaf37-bdb5-4f57-ab0e-fe25245c6b80.png">

However when you take a look at the proposal details:

https://lava-testnet.nodejumper.io:1317/cosmos/gov/v1beta1/proposals/32

```
"voting_start_time": "2023-02-21T01:37:39.427455892Z",
"voting_end_time": "2023-02-21T13:37:39.427455892Z"
```

It says that voting starts at `2023-02-21T01:37:39 UTC`, which is wrong and 4 hours ahead the actual creation time, voting end time is moved to 4 hours respectively, which makes explorers/bots to show misleading information.

## Expected Behavior

```
"voting_start_time": "2023-02-20T21:37:39.427455892Z",
"voting_end_time": "2023-02-21T09:37:39.427455892Z"
```

## Current Behavior

```
"voting_start_time": "2023-02-21T01:37:39.427455892Z",
"voting_end_time": "2023-02-21T13:37:39.427455892Z"
```

**Comment by SeanZoR** [comment]
Now resolved. thank you.
