### ISSUE TITLE
Opps! Looks like something went wrong :( If you have time please report it to our github

### ISSUE THREAD

**Issue by AshenTr** [lavanet/lava#581]
"Opps! Looks like something went wrong :( If you have time please report it to our github"
https://bd.lavanet.xyz/accounts/lava@1us59u4u0t5l243hmkvrz5fvthpxu0c20axm4ra
Monitoring https://github.com/forbole/big-dipper-2.0-cosmos/issues/63 | Software upgrade v0.15.1 after "Yes"

![26062023](https://github.com/lavanet/lava/assets/131547591/20c716fb-3027-4beb-b06d-63e30e2ab36e)

**Comment by ranlavanet** [comment]
Wrong repository to report to :) closing the issue and reopening in the right repo
